name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install yc cli
        id: install-cli
        run: |
          apt update && apt install -y curl jq gettext
          curl -f -s -LO https://storage.yandexcloud.net/yandexcloud-yc/install.sh
          bash install.sh -i /opt/yc -n
      - name: login
        id: login
        run: |
          export PATH="/opt/yc/bin:$PATH"
          yc config set token "${{ secrets.YC_TOKEN }}"
          echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
      - uses: actions/checkout@v4
      - name: build and push
        env:
          CR_REGISTRY: crpunrjbuup33ugn5q54
          CR_REPOSITORY: squirrelsquery
        run: |
          docker build . -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY --file Dockerfile
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY
      - name: deploy
        env:
          CR_REGISTRY: crpunrjbuup33ugn5q54
          CR_REPOSITORY: squirrelsquery
        run: |
          export PATH="/opt/yc/bin:$PATH"
          yc serverless container revision deploy --container-name squirrelsquery --image "cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest" --cores 1 --memory 128mb --core-fraction 5 --concurrency 16 --execution-timeout 10s --cloud-id b1gbs9scavfpnat45f6q --folder-name default --service-account-id ajeunnejdm7jnb3fkc1f --environment TOKEN='${{ secrets.TOKEN }}' --network-id enp01bv6bibq2up3p5ot --zone-instances-limit 1 --zone-requests-limit 100